language: go
services:
  - mysql
  - redis
go: 
 - 1.9.x

before_script:
 - "mysql -e 'create database gintonic;'"

before_install:
  - go get github.com/tcnksm/ghr
  - go get github.com/axw/gocov/gocov
  - go get github.com/mattn/goveralls
script:
 - export ENV=test
 - export CONFIGDIR=/tmp/configs
 - export GTC_DB_HOST=localhost
 - export GTC_DB_PORT=3306
 - export GTC_DB_USER=root
 - export GTC_DB_NAME=gintonic
 - export GTC_REDIS_HOST=localhost
 - export GTC_REDIS_PORT=6379
 - ./test.sh